services:
  mc-skin-api:
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./accessories
        target: /app/accessories
        read_only: true
      - type: bind
        source: ./skins
        target: /app/skins
        read_only: true